---
title: "influencer-marketing-analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(ggplot2)

age_levels <- c(
  "18-25", 
  "26-35"
)

ed_levels <- c(
  "Senior high school degree or equivalent",
  "Bachelor's degree",                     
  "Master's degree or higher"              
)

frq_levels <-c(
  "Less than once a month",
  "About once a month",
  "About once a week",
  "About two to three times a week",
  "About once a day",
  "More than once a day" 
)

likert_levels <- c(
  "Not likely at all",
  "Slightly likely",   
  "Moderately Likely",
  "Very likely"       
)

d_infmkt <- read_csv(
  './data/influencer-marketing-data.csv',
  col_types = cols(
    col_factor(),
    col_factor(ordered = TRUE, levels = age_levels),
    col_factor(ordered = TRUE, levels = ed_levels),
    col_factor(ordered = TRUE, levels = frq_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    
  ))
```


```{r}

d_infmkt %>%
  ggplot(aes(
    x = gender
  )) + geom_bar()

d_infmkt %>%
  ggplot(aes(
    x = age
  )) + geom_bar()

d_infmkt %>%
  ggplot(aes(
    x = education
  )) + geom_bar()+coord_flip()


d_infmkt %>%
  ggplot(aes(
    x = frequency
  )) + geom_bar()+coord_flip()

```

```{r}
d_infmkt <- d_infmkt %>%
  mutate(    
    Female = gender == 'Female',
    across(
      .cols = c(frequency, informativeness, entertainment),
      .fns = as.numeric,
      .names='{.col}_coded'
      ))

```

```{r}
d_infmkt %>%
  ggplot(aes(x = frequency, y = informativeness, colour = Female)) +
  geom_jitter()

d_infmkt %>%
  ggplot(aes(x = frequency, y = entertainment, colour = Female)) +
  geom_jitter()

d_infmkt %>%
  ggplot(aes(x = informativeness, y = entertainment, colour = Female)) +
  geom_jitter()

```

```{r}

d_infmkt %>%
  ggplot(aes(x = gender, y = frequency)) +
  geom_jitter()

d_infmkt %>%
  ggplot(aes(x = gender, y = entertainment)) +
  geom_jitter()

d_infmkt %>%
  ggplot(aes(x = gender, y = informativeness)) +
  geom_jitter()

```

```{r}
d_infmkt %>%
  cor.test(~ frequency_coded + informativeness_coded, data = ., method = 'spearman', exact = FALSE)

d_infmkt %>%
  cor.test(~ frequency_coded + entertainment_coded, data = ., method = 'spearman', exact = FALSE)

d_infmkt %>%
  cor.test(~ entertainment_coded + informativeness_coded, data = ., method = 'spearman', exact = FALSE)

```

```{r}

d_infmkt <- d_infmkt %>%
  mutate(
    inf_true = informativeness %>%
      recode(
        "Not likely at all" = FALSE,
        "Slightly likely" = TRUE,
        "Moderately Likely" = TRUE,
        "Very likely" = TRUE 
      )
  )

d_infmkt <- d_infmkt %>%
  mutate(
    ent_true = entertainment %>%
      recode(
        "Not likely at all" = FALSE,
        "Slightly likely" = TRUE,
        "Moderately Likely" = TRUE,
        "Very likely" = TRUE 
      )
  )

d_infmkt %>%
  wilcox.test(
    frequency_coded ~ inf_true,
    data = .
  )


```



